version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: alkamus
    volumes:
      - /usr/local/var/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - db
    